### ISSUE TITLE
Issue with exe file UI

### ISSUE THREAD

**Issue by SirReubs** [Puma605/Legend-Of-Zelda-remake-My-version-#2] opened 2023-06-09 09:25 UTC
The game UI is frozen on the main menu, you can scroll on the main menu but it doesn't register on the UI.
This is for the latest release with the EXE file.

**Comment by Puma605** [comment] 2023-06-09 09:34
Are u sure ur pressing and not the mouse left click?
This game doesn't use the mouse at all.

**Comment by SirReubs** [comment] 2023-06-09 09:53
I succesfully started a new game by using enter and w and s but the UI doesn't change\
I could hear the audio changing

**Comment by Puma605** [comment] 2023-06-09 09:57
Try opening and closing the game again, the problem might be with the computer but if it occurs again update me

**Comment by SirReubs** [comment] 2023-06-09 09:58
It definitely happened again

**Comment by Puma605** [comment] 2023-06-09 10:26
I will fix it later, but does the actual game start if u click on it the new game button?

**Comment by SirReubs** [comment] 2023-06-09 12:41
I have no clue

**Comment by Puma605** [comment] 2023-06-13 10:55
the issue is resolved in the newest release

**Closed as completed by Puma605** 2023-06-13 10:55 UTC
Labels: bug
